### ISSUE TITLE
fov feature

### ISSUE THREAD

**Issue by YopSolo** [totologic/daedalus-lib#1]
hello, i have ran a test for fov feature
http://www.yopsolo.fr/wp/2016/01/20/fov-daedalus-test/

if i do something like

``` actionscript
_ddlsView.drawEntity(_entityAI);
if (_ddlsFov.isInField(_entity2AI))
{
    _ddlsView.drawEntity(_entity2AI);
}
```

_entityAI disapear when _entity2AI is in his FOV

To avoid this i readraw all entites witch is ok if i only have 2 entites ^^

``` actionscript
if (_ddlsFov.isInField(_entity2AI))
{
    _ddlsView.drawEntities(_ddlsEntities);
}
```

am I missing something ?

**Comment by totologic** [comment]
A call of drawEntity or drawEntities automatically call a clear.

This can be avoided by passing a false value as 2nd parameter. Look the true default value in source code:

function drawEntity(entity:DDLSEntityAI, cleanBefore:Boolean=true):void
function drawEntities(vEntities:Vector.<DDLSEntityAI>, cleanBefore:Boolean=true):void
